# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-19 08:59
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=255, verbose_name='文章标题')),
                ('a_info', models.CharField(max_length=500, verbose_name='备注')),
                ('a_content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='文章内容')),
                ('a_img', models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='文章图片')),
                ('a_addtime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('a_updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '美文信息',
                'ordering': ['-a_addtime'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=255, verbose_name='标签名')),
                ('t_info', models.CharField(max_length=300, verbose_name='描述')),
                ('t_createtime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '标签信息',
            },
        ),
        migrations.AddField(
            model_name='art',
            name='a_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Tag'),
        ),
    ]
